name: Build

on:
  push:
    branches:
      - jazzy
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: ros:jazzy
    steps:
      - name: Install global dependencies
        run: |
          apt update && apt install --no-install-recommends -y \
            python3-pip python3-colcon-coveragepy-result python3-pytest-cov
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Build and test
        uses: ros-tooling/action-ros-ci@0.4.8
        with:
          package-name: rqt_lifecycle_manager
          target-ros2-distro: jazzy
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }
          skip-tests: false
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ros_ws/lcov/total_coverage.info,ros_ws/coveragepy/.coverage
          flags: unittests
          name: codecov-umbrella
          slug: ajtudela/rqt_lifecycle_manager
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          report_type: test_results
